# Generated by Django 4.0.3 on 2022-04-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board_height', models.PositiveIntegerField(choices=[(26, '26'), (32, '32'), (38, '38'), (50, '50'), (60, '60')])),
                ('board_class', models.CharField(max_length=10)),
                ('stock', models.CharField(choices=[('Sjekac 1', 'Sjekac 1'), ('Sjekac 2', 'Sjekac 2'), ('Skladiste', 'Skladiste')], default=('Skladiste', 'Skladiste'), max_length=50)),
                ('board_lengths', models.CharField(default='[]', max_length=100)),
                ('board_measurement_type', models.CharField(choices=[('UK', 'Unutar kosine'), ('PK', 'Pola kosine'), ('JK', 'Jedna kosina'), ('PS', 'Puna sirina'), ('DS', 'Dvije sirine')], max_length=30)),
                ('board_type', models.CharField(choices=[('MIX', 'Mix'), ('SAMICA', 'Samica'), ('POLUSAMICA', 'Polusamica'), ('OKRAJCENA', 'Okrajcena')], max_length=30)),
                ('closed', models.BooleanField(default=False)),
                ('last_change_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WoodType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wood_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackageBoardLengthWidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(default=200)),
                ('width', models.PositiveIntegerField()),
                ('width2', models.PositiveIntegerField(null=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='wood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.woodtype'),
        ),
    ]
